### ISSUE TITLE
Sample configuration?

### ISSUE THREAD

**Issue by teeler** [niallo/PyNanny#1]
A configuration reference would be helpful as well, for those of us who might have forgotten the way. ;)

**Comment by niallo** [comment]
This one doesn't have a config language yet - my thought was to implement something like the mwbuild4 language using Python ConfigParser. The tests should contain enough to demo most of the features though, if you can afford to go procedural.

How much declarative support do you need?

**Comment by teeler** [comment]
ah, now I get what I was looking at. I don't think I need any, actually, this is great, thanks dude. ;)
